version: '3.8'

services:
  db:
    container_name: db
    build: ./requirements/db/.  
    image: db
    volumes:
      - mariadb:/var/lib/mysql
    env_file:
      - .env
    networks:
      - inception
    restart: always
  wp:
    container_name: wp
    build: ./requirements/wp/.
    image: wp
    depends_on:
      - db
    volumes:
      - wordpress:/var/www/html
    env_file:
      - .env
    networks:
      - inception
    restart: always
  http:
    container_name: http
    build: ./requirements/http/.
    image: http
    ports:
      - "443:443"
    depends_on:
      - wp
    volumes:
      - wordpress:/var/www/html
    networks:
      - inception
    env_file:
      - .env
    restart: always

volumes:
  wordpress:
    name: wordpress
    driver: local
    driver_opts:
      device: /root/data/wordpress
      o: bind                     
      type: none                         
  mariadb:
    name: mariadb
    driver: local
    driver_opts:
      device: /root/data/mariadb
      o: bind
      type: none


networks:
  inception:
    name: inception
    driver: bridge
